global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8080' ]

  - job_name: 'api-gateway-all'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: [ 'api-gateway:8080' ]

  - job_name: 'auth-service'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'auth-service:8080' ]

  - job_name: 'guest-service'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'guest-service:8083' ]

  - job_name: 'room-service'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'room-service:9000' ]

  - job_name: 'reservation-service'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'reservation-service:9000' ]


  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]